development:
  secret_key_base: c5681369946d41cef75602da03bce3aa5b6031771ff1c12df56b6de774abcda87b5ef5a3bf01bf406f5e79c80a026fc5c43aef0abd6a64fad6f14da4a1de143b
  devise_secret_key: c5681369946d41cef75602da03bce3aa5b6031771ff1c12df56b6de774abcda87b5ef5a3bf01bf406f5e79c80a026fc5c43aef0abd6a64fad6f14da4a1de143b

  recaptcha_public_key: my_public_key
  recaptcha_private_key: my_private_key


test:
  secret_key_base: c5681369946d41cef75602da03bce3aa5b6031771ff1c12df56b6de774abcda87b5ef5a3bf01bf406f5e79c80a026fc5c43aef0abd6a64fad6f14da4a1de143b
  devise_secret_key: c5681369946d41cef75602da03bce3aa5b6031771ff1c12df56b6de774abcda87b5ef5a3bf01bf406f5e79c80a026fc5c43aef0abd6a64fad6f14da4a1de143b
  recaptcha_public_key: my_public_key
  recaptcha_private_key: my_private_key
  kontoapi_key: the_kontoapi_key
  fastbill_email: my_email
  fastbill_api_key: my_fastbill_api_key
  cleverreach_api_key: cleverreach_key
  cleverreach_list_id: group_number_as_integer
  discourse_secret:
  discourse_url:
  actionmailer_address:
  actionmailer_username:
  actionmailer_password:

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
  recaptcha_public_key: my_public_key
  recaptcha_private_key: my_private_key
  # Heroku-TODO: Mailserver settings
  actionmailer_address: <%= ENV["ACTIONMAILER_ADDRESS"] %>
  actionmailer_username: <%= ENV["ACTIONMAILER_USERNAME"] %>
  actionmailer_password: <%= ENV["ACTIONMAILER_PASSWORD"] %>
